# Generated by Django 3.2.12 on 2022-03-28 08:11

import django.utils.timezone
from django.db import migrations, models

import smart_register.i18n.fields


class Migration(migrations.Migration):

    dependencies = [
        ("i18n", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message",
            name="locale",
            field=smart_register.i18n.fields.LanguageField(
                choices=[("uk-ua", "український"), ("en-us", "English"), ("pl-pl", "Polskie")],
                default="en-us",
                max_length=10,
                null=True,
                verbose_name="Language",
            ),
        ),
    ]
