# Generated by Django 3.2.12 on 2022-04-12 12:23

from django.db import migrations, models

import smart_register.i18n.fields


class Migration(migrations.Migration):
    dependencies = [
        ("i18n", "0002_auto_20220328_0811"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="locale",
            field=smart_register.i18n.fields.LanguageField(
                choices=[
                    ("uk-ua", "український | Ukrainian"),
                    ("en-us", "English | English"),
                    ("pl-pl", "Polskie | Polish"),
                ],
                default="en-us",
                max_length=10,
                null=True,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
