# Generated by Django 3.2.13 on 2022-04-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("i18n", "0007_message_msgcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="orphan",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="msgcode",
            field=models.CharField(max_length=512, verbose_name="Code"),
        ),
    ]
