# Generated by Django 3.2.12 on 2022-03-07 11:08

from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [CITextExtension()]
