# Generated by Django 3.2.12 on 2022-03-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20220308_2049"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flexformfield",
            options={
                "ordering": ["ordering"],
                "verbose_name": "FlexForm Field",
                "verbose_name_plural": "FlexForm Fields",
            },
        ),
        migrations.AddField(
            model_name="flexformfield",
            name="ordering",
            field=models.PositiveIntegerField(default=0, verbose_name="ordering"),
        ),
        migrations.AlterUniqueTogether(
            name="flexformfield",
            unique_together={("flex_form", "name")},
        ),
    ]
