# Generated by Django 3.2.12 on 2022-03-13 12:09

import concurrency.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_optionset_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optionset",
            name="columns",
            field=models.CharField(
                blank=True,
                default="label",
                help_text="column order. Es: 'pk,parent,label' or 'pk,label'",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="optionset",
            name="version",
            field=concurrency.fields.VersionField(default=0, help_text="record revision number"),
        ),
    ]
