# Generated by Django 3.2.12 on 2022-03-13 12:10

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_auto_20220313_1209"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optionset",
            name="version",
            field=concurrency.fields.IntegerVersionField(default=0, help_text="record revision number"),
        ),
    ]
