# Generated by Django 3.2.12 on 2022-03-13 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_formset_max_num"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formset",
            old_name="required",
            new_name="min_num",
        ),
    ]
