# Generated by Django 3.2.12 on 2022-03-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_formset_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="flexformfield",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
