# Generated by Django 3.2.12 on 2022-03-28 06:47

import django.contrib.postgres.fields.citext
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_validator_trace"),
    ]

    operations = [
        migrations.AddField(
            model_name="optionset",
            name="comment",
            field=models.CharField(blank=True, default="#", max_length=1),
        ),
        migrations.AlterField(
            model_name="optionset",
            name="columns",
            field=models.CharField(
                blank=True,
                default="0,0,-1",
                help_text="column order. Es: 'pk,parent,label' or 'pk,label'",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="optionset",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(
                max_length=100, unique=True, validators=[django.core.validators.RegexValidator("[a-z0-9-_]")]
            ),
        ),
    ]
