# Generated by Django 3.2.12 on 2022-04-02 11:52

import concurrency.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_optionset_last_update_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="validator",
            name="last_update_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="validator",
            name="version",
            field=concurrency.fields.AutoIncVersionField(default=0, help_text="record revision number"),
        ),
    ]
