# Generated by Django 3.2.13 on 2022-04-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_auto_20220402_1152"),
    ]

    operations = [
        migrations.AddField(
            model_name="validator",
            name="active",
            field=models.BooleanField(blank=True, default=False, null=False),
        ),
        migrations.AddField(
            model_name="validator",
            name="draft",
            field=models.BooleanField(blank=True, default=False, null=False),
        ),
    ]
