# Generated by Django 3.2.13 on 2022-04-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_auto_20220417_0919"),
    ]

    operations = [
        migrations.AddField(
            model_name="optionset",
            name="languages",
            field=models.CharField(
                blank=True, default="-;-;", help_text="language code of each column.", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="optionset",
            name="locale",
            field=models.CharField(default="en-us", help_text="default language code", max_length=5),
        ),
        migrations.AddField(
            model_name="optionset",
            name="parent_col",
            field=models.IntegerField(default=-1, help_text="Column number of the indicating parent element"),
        ),
        migrations.AddField(
            model_name="optionset",
            name="pk_col",
            field=models.IntegerField(default=0, help_text="ID column number"),
        ),
    ]
