# Generated by Django 3.2.13 on 2022-05-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_auto_20220420_1248"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validator",
            name="message",
            field=models.CharField(
                blank=True, help_text="Default error message if validator return 'false'.", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="validator",
            name="target",
            field=models.CharField(
                choices=[("form", "Form"), ("field", "Field"), ("formset", "Formset"), ("module", "Module")],
                max_length=10,
            ),
        ),
    ]
