# Generated by Django 3.2.13 on 2022-05-06 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_auto_20220505_1751"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flexform",
            options={"verbose_name": "Flex Form", "verbose_name_plural": "Flex Forms"},
        ),
        migrations.AlterModelOptions(
            name="flexformfield",
            options={"ordering": ["ordering"], "verbose_name": "Flex Field", "verbose_name_plural": "Flex Fields"},
        ),
    ]
