# Generated by Django 3.2.16 on 2023-02-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_auto_20230126_1226"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="organization",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="project",
            managers=[],
        ),
    ]
