# Generated by Django 3.2.16 on 2023-03-07 11:39

import aurora.core.compat
import aurora.core.models
import django.contrib.postgres.fields.citext
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_auto_20230214_1915"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flexformfield",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(
                blank=True, max_length=100, validators=[django.core.validators.RegexValidator("^[a-z_0-9]*$")]
            ),
        ),
        migrations.AlterField(
            model_name="flexformfield",
            name="regex",
            field=aurora.core.compat.RegexField(
                blank=True, null=True, validators=[aurora.core.models.RegexPatternValidator()]
            ),
        ),
    ]
