# Generated by Django 3.2.16 on 2023-03-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_auto_20230307_1139"),
    ]

    operations = [
        migrations.AddField(
            model_name="flexformfield",
            name="validation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
