# Generated by Django 3.2.16 on 2023-03-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_flexformfield_validation"),
    ]

    operations = [
        migrations.AddField(
            model_name="flexform",
            name="advanced",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
