# Generated by Django 3.2.18 on 2023-11-23 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_auto_20230321_0604"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flexform",
            name="project",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.project"),
        ),
        migrations.AlterField(
            model_name="project",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="projects", to="core.organization"
            ),
        ),
    ]
