# Generated by Django 4.2.10 on 2024-05-03 06:31
from django.contrib.postgres.operations import CreateCollation
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_alter_project_slug"),
    ]

    operations = [
        CreateCollation(
            "_",
            provider="icu",
            locale="und-u-ks-level2",
            deterministic=False,
        ),
    ]
