# Generated by Django 3.2.12 on 2022-03-12 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_registration_public_key2"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="data2",
            new_name="storage",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="public_key2",
        ),
    ]
