# Generated by Django 3.2.12 on 2022-03-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0006_remove_record_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="intro",
            field=models.TextField(blank=True, null=True),
        ),
    ]
