# Generated by Django 3.2.12 on 2022-03-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0007_registration_intro"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="slug",
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
