# Generated by Django 3.2.12 on 2022-03-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0011_auto_20220321_0507"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="locale",
            field=models.CharField(
                choices=[("en-us", "English"), ("pl-pl", "Polskie"), ("uk-ua", "український")],
                default="en",
                max_length=10,
            ),
        ),
    ]
