# Generated by Django 3.2.12 on 2022-03-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0014_registration_footer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="locale",
            field=models.CharField(
                choices=[("uk-ua", "український"), ("en-us", "English"), ("pl-pl", "Polskie")],
                default="en-us",
                max_length=10,
            ),
        ),
    ]
