# Generated by Django 3.2.12 on 2022-03-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0019_alter_record_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
