# Generated by Django 3.2.12 on 2022-04-02 09:57

import concurrency.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0020_alter_record_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="last_update_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="version",
            field=concurrency.fields.AutoIncVersionField(default=0, help_text="record revision number"),
        ),
    ]
