# Generated by Django 3.2.12 on 2022-04-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0022_record_remote_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="fields",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="ignored",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
