# Generated by Django 3.2.12 on 2022-04-12 14:08

from django.db import migrations, models
import smart_register.registration.fields


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0023_alter_registration_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="locales",
            field=smart_register.registration.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("uk-ua", "український | Ukrainian"),
                        ("en-us", "English | English"),
                        ("pl-pl", "Polskie | Polish"),
                    ],
                    max_length=10,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="locale",
            field=models.CharField(
                choices=[
                    ("uk-ua", "український | Ukrainian"),
                    ("en-us", "English | English"),
                    ("pl-pl", "Polskie | Polish"),
                ],
                default="en-us",
                max_length=10,
                verbose_name="Default locale",
            ),
        ),
    ]
