# Generated by Django 3.2.13 on 2022-04-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0025_auto_20220422_1344"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="fields",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="record",
            name="files",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="ignored",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="footer",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="intro",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
