# Generated by Django 3.2.13 on 2022-05-13 13:53

from django.db import migrations

SQL = """
BEGIN;
ALTER TABLE "registration_record" ADD COLUMN IF NOT EXISTS  "fields" jsonb NULL;
ALTER TABLE "registration_record" ADD COLUMN IF NOT EXISTS  "files" bytea NULL;
ALTER TABLE "registration_record" ADD COLUMN IF NOT EXISTS  "unique_field" varchar(255) NULL;
ALTER TABLE "registration_registration" ADD COLUMN IF NOT EXISTS "unique_field" varchar(255) NULL;
COMMIT;
"""

REVERSE = """
BEGIN;
ALTER TABLE "registration_record" DROP CONSTRAINT "registration_record_registration_id_unique_field_2701a3c6_uniq";
ALTER TABLE "registration_registration" DROP COLUMN "unique_field" CASCADE;
ALTER TABLE "registration_record" DROP COLUMN "unique_field" CASCADE;
ALTER TABLE "registration_record" DROP COLUMN "files" CASCADE;
ALTER TABLE "registration_record" DROP COLUMN "fields" CASCADE;
COMMIT;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_alter_validator_target"),
        ("registration", "0031_auto_20220512_1125"),
    ]

    operations = [
        migrations.RunSQL(SQL, REVERSE),
        # migrations.RunSQL(
        #     'CREATE INDEX CONCURRENTLY "registration_record_unique_field_5edac906" '
        #     'ON "registration_record" ("unique_field");'
        # ),
        migrations.RunSQL(
            'CREATE INDEX CONCURRENTLY "registration_record_unique_field_5edac906_like" '
            'ON "registration_record" ("unique_field" varchar_pattern_ops);'
        ),
        migrations.RunSQL(
            'ALTER TABLE "registration_record" '
            'ADD CONSTRAINT "registration_record_registration_id_unique_field_2701a3c6_uniq" '
            'UNIQUE ("registration_id", "unique_field");'
        ),
        # migrations.AddField(
        #     model_name='record',
        #     name='fields',
        #     field=models.JSONField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='record',
        #     name='files',
        #     field=models.BinaryField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='record',
        #     name='unique_field',
        #     field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        # ),
        # migrations.AddField(
        #     model_name='registration',
        #     name='unique_field',
        #     field=models.CharField(blank=True,
        #     help_text='Form field to be used as unique key', max_length=255, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='registration',
        #     name='scripts',
        #     field=models.ManyToManyField(blank=True,
        #     limit_choices_to={'target': 'script'}, related_name='script_for', to='core.Validator'),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='record',
        #     unique_together={('registration', 'unique_field')},
        # ),
    ]
