# Generated by Django 3.2.13 on 2022-06-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_validator_target'),
        ('registration', '0033_auto_20220604_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='index1',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='index2',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='index3',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
