# Generated by Django 3.2.15 on 2022-08-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0034_auto_20220604_2141"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="unique_field_path",
            field=models.CharField(
                blank=True, help_text="JMESPath expression to retrieve unique field", max_length=1000, null=True
            ),
        ),
    ]
