# Generated by Django 3.2.13 on 2022-05-06 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registration", "0027_alter_registration_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Counter",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day", models.DateField(blank=True, db_index=True, null=True)),
                ("records", models.IntegerField(blank=True, default=0, null=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "registration",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="registration.registration"),
                ),
            ],
            options={
                "ordering": ("-day",),
                "get_latest_by": "day",
                "unique_together": {("registration", "day")},
            },
        ),
    ]
