# Generated by Django 3.2.16 on 2023-03-10 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("registration", "0038_auto_20230310_1715"),
        ("core", "0050_auto_20230307_1139"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationrole",
            name="valid_from",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="registrationrole",
            name="valid_until",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="registrationrole",
            name="registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="roles", to="registration.registration"
            ),
        ),
        migrations.CreateModel(
            name="OrganizationRole",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("valid_from", models.DateField(default=django.utils.timezone.now)),
                ("valid_until", models.DateField(default=None, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="users", to="core.organization"
                    ),
                ),
                ("role", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="auth.group")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("organization", "user", "role")},
            },
        ),
    ]
