# Generated by Django 3.2.15 on 2022-09-30 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0038_alter_registration_unique_field"),
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationrole",
            name="registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="roles", to="registration.registration"
            ),
        ),
    ]
