# Generated by Django 3.2.15 on 2022-09-30 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0002_alter_registrationrole_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationrole",
            name="valid_from",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="registrationrole",
            name="valid_until",
            field=models.DateField(default=None, null=True),
        ),
    ]
