# Generated by Django 3.2.16 on 2023-02-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0004_organizationrole"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationrole",
            name="valid_until",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
