# Generated by Django 3.2.16 on 2023-03-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0006_auto_20230310_1941"),
    ]

    operations = [
        migrations.AddField(
            model_name="aurorauser",
            name="ad_uuid",
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="aurorauser",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="aurorauser",
            name="job_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
