# Generated by Django 3.2.16 on 2023-03-19 06:57

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("security", "0009_aurorarole"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="registrationrole",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="registrationrole",
            name="registration",
        ),
        migrations.RemoveField(
            model_name="registrationrole",
            name="role",
        ),
        migrations.RemoveField(
            model_name="registrationrole",
            name="user",
        ),
        migrations.CreateModel(
            name="AuroraGroup",
            fields=[],
            options={
                "verbose_name": "group",
                "verbose_name_plural": "groups",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="AuroraPermission",
            fields=[],
            options={
                "verbose_name": "permission",
                "verbose_name_plural": "permissions",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.permission",),
            managers=[
                ("objects", django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.CreateModel(
            name="AuroraUser",
            fields=[],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="aurorarole",
            options={"verbose_name": "role", "verbose_name_plural": "roles"},
        ),
        migrations.DeleteModel(
            name="OrganizationRole",
        ),
        migrations.DeleteModel(
            name="RegistrationRole",
        ),
    ]
