# Generated by Django 3.2.12 on 2022-03-26 21:39

from django.db import migrations, models

import aurora.i18n.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "locale",
                    aurora.i18n.fields.LanguageField(
                        choices=[("en-us", "English"), ("pl-pl", "Polskie"), ("uk-ua", "український")],
                        default="en-us",
                        max_length=10,
                        null=True,
                        verbose_name="Language",
                    ),
                ),
                ("msgid", models.TextField()),
                ("msgstr", models.TextField(blank=True, null=True)),
                ("md5", models.CharField(db_index=True, max_length=512, verbose_name="MD5")),
            ],
        ),
    ]
