# Generated by Django 3.2.12 on 2022-04-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("i18n", "0003_auto_20220412_1223"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="auto",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="draft",
            field=models.BooleanField(default=True),
        ),
    ]
