# Generated by Django 3.2.13 on 2022-04-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("i18n", "0005_auto_20220421_0941"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="md5",
            field=models.CharField(max_length=512, unique=True, verbose_name="MD5"),
        ),
    ]
