# Generated by Django 3.2.13 on 2022-04-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("i18n", "0006_alter_message_md5"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="msgcode",
            field=models.CharField(default="", max_length=512, verbose_name="MD5"),
            preserve_default=False,
        ),
    ]
