# Generated by Django 3.2.16 on 2022-12-02 10:11

from django.db import migrations

import aurora.i18n.fields


class Migration(migrations.Migration):

    dependencies = [
        ("i18n", "0008_auto_20220429_2218"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="locale",
            field=aurora.i18n.fields.LanguageField(
                choices=[
                    ("en-us", "English | English"),
                    ("uk-ua", "український | Ukrainian"),
                    ("pl-pl", "Polskie | Polish"),
                    ("ar-ae", " | عربيArabic"),
                    ("es-es", "Español | Spanish"),
                    ("fr-fr", "Français | French"),
                    ("pt-pt", "Português"),
                    ("ta-ta", "தமிழ் | Tamil"),
                    ("si-si", "සිංහල | Sinhala"),
                ],
                db_index=True,
                default="en-us",
                max_length=10,
                null=True,
                verbose_name="Language",
            ),
        ),
    ]
