# Generated by Django 3.2.16 on 2023-01-25 09:42

import aurora.i18n.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("i18n", "0010_alter_message_locale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="locale",
            field=aurora.i18n.fields.LanguageField(
                choices=[
                    ("en-us", "English | English"),
                    ("ar-ae", " | عربيArabic"),
                    ("cs-cz", "čeština | Czech"),
                    ("de-de", "Deutsch"),
                    ("es-es", "Español | Spanish"),
                    ("fr-fr", "Français | French"),
                    ("hu-hu", "Magyar | Hungarian"),
                    ("it-it", "Italiano"),
                    ("pl-pl", "Polskie | Polish"),
                    ("pt-pt", "Português"),
                    ("ro-ro", "Română"),
                    ("ru-ru", "Русский | Russian"),
                    ("si-si", "සිංහල | Sinhala"),
                    ("ta-ta", "தமிழ் | Tamil"),
                    ("uk-ua", "український | Ukrainian"),
                    ("hi-hi", "हिंदी"),
                ],
                db_index=True,
                default="en-us",
                max_length=10,
                null=True,
                verbose_name="Language",
            ),
        ),
    ]
