# Generated by Django 3.2.12 on 2022-03-04 09:01

import django.contrib.postgres.fields.citext
import django.db.models.deletion
import strategy_field.fields
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        CITextExtension(),
        migrations.CreateModel(
            name='FlexForm',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    django.contrib.postgres.fields.citext.CICharField(
                        max_length=255, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Validator',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    django.contrib.postgres.fields.citext.CICharField(
                        max_length=255, unique=True
                    ),
                ),
                ('message', models.CharField(max_length=255)),
                ('code', models.TextField(blank=True, null=True)),
                (
                    'target',
                    models.CharField(
                        choices=[('form', 'Form'), ('field', 'Field')], max_length=5
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='FormSet',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    django.contrib.postgres.fields.citext.CICharField(
                        max_length=255, unique=True
                    ),
                ),
                (
                    'flex_form',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.flexform'
                    ),
                ),
                (
                    'parent',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='formsets',
                        to='core.flexform',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='flexform',
            name='validator',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={'target': 'form'},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='core.validator',
            ),
        ),
        migrations.CreateModel(
            name='FlexFormField',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('label', models.CharField(max_length=30)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('field', strategy_field.fields.StrategyClassField()),
                ('choices', models.CharField(blank=True, max_length=2000, null=True)),
                ('required', models.BooleanField(default=False)),
                (
                    'flex_form',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='fields',
                        to='core.flexform',
                    ),
                ),
                (
                    'validator',
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={'target': 'field'},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='core.validator',
                    ),
                ),
            ],
            options={
                'unique_together': {('name', 'flex_form')},
            },
        ),
    ]
