# Generated by Django 3.2.12 on 2022-03-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formset',
            options={'verbose_name': 'FormSet', 'verbose_name_plural': 'FormSets'},
        ),
        migrations.AddField(
            model_name='formset',
            name='extra',
            field=models.IntegerField(default=0),
        ),
    ]
