# Generated by Django 3.2.12 on 2022-03-08 10:39

from django.db import migrations
import django.forms.fields
import strategy_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customfieldtype",
            name="base_type",
            field=strategy_field.fields.StrategyClassField(default=django.forms.fields.CharField),
        ),
    ]
