# Generated by Django 3.2.12 on 2022-03-06 08:25

from django.db import migrations, models
import django_regex.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexform',
            options={'verbose_name': 'FlexForm', 'verbose_name_plural': 'FlexForms'},
        ),
        migrations.AlterModelOptions(
            name='flexformfield',
            options={'verbose_name': 'FlexForm Field', 'verbose_name_plural': 'FlexForm Fields'},
        ),
        migrations.AddField(
            model_name='flexformfield',
            name='regex',
            field=django_regex.fields.RegexField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optionset',
            name='separator',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
