# Generated by Django 3.2.12 on 2022-03-06 09:09

from django.db import migrations
import django_regex.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220306_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='regex',
            field=django_regex.fields.RegexField(blank=True, null=True),
        ),
    ]
