# Generated by Django 3.2.12 on 2022-03-08 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_customfieldtype_base_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customfieldtype",
            name="choices",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="customfieldtype",
            name="required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customfieldtype",
            name="validator",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"target": "field"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.validator",
            ),
        ),
        migrations.AlterField(
            model_name="customfieldtype",
            name="clean",
            field=models.TextField(blank=True, default=""),
        ),
    ]
