# Generated by Django 3.2.12 on 2022-03-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20220308_1056"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customfieldtype",
            name="clean",
        ),
    ]
