# Generated by Django 3.2.12 on 2022-03-10 15:20

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_auto_20220310_1033"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formset",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="formset",
            unique_together={("flex_form", "name")},
        ),
    ]
