# Generated by Django 3.2.12 on 2022-03-10 18:09

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_auto_20220310_1520"),
    ]

    operations = [
        migrations.AddField(
            model_name="flexform",
            name="version",
            field=concurrency.fields.AutoIncVersionField(default=0, help_text="record revision number"),
        ),
    ]
