# Generated by Django 3.2.12 on 2022-03-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_flexform_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flexform",
            name="version",
        ),
        migrations.AddField(
            model_name="formset",
            name="required",
            field=models.IntegerField(default=0),
        ),
    ]
