# Generated by Django 3.2.12 on 2022-03-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_optionset_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="formset",
            name="max_num",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
