# Generated by Django 3.2.12 on 2022-03-14 06:57

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_formset_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="optionset",
            name="description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="optionset",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(max_length=100, unique=True),
        ),
    ]
