# Generated by Django 3.2.12 on 2022-03-15 16:39

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_auto_20220314_0657"),
    ]

    operations = [
        migrations.AddField(
            model_name="flexform",
            name="version",
            field=concurrency.fields.IntegerVersionField(default=0, help_text="record revision number"),
        ),
        migrations.AddField(
            model_name="flexformfield",
            name="version",
            field=concurrency.fields.IntegerVersionField(default=0, help_text="record revision number"),
        ),
        migrations.AddField(
            model_name="formset",
            name="version",
            field=concurrency.fields.IntegerVersionField(default=0, help_text="record revision number"),
        ),
    ]
