# Generated by Django 3.2.12 on 2022-03-18 05:16

import django.forms.fields
from django.db import migrations, models

import smart_register.core.compat
import smart_register.core.forms


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_auto_20220315_1639"),
    ]

    operations = [
        migrations.AddField(
            model_name="formset",
            name="description",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="formset",
            name="title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="customfieldtype",
            name="base_type",
            field=smart_register.core.compat.StrategyClassField(default=django.forms.fields.CharField),
        ),
        migrations.AlterField(
            model_name="customfieldtype",
            name="regex",
            field=smart_register.core.compat.RegexField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="flexform",
            name="base_type",
            field=smart_register.core.compat.StrategyClassField(default=smart_register.core.forms.FlexFormBaseForm),
        ),
        migrations.AlterField(
            model_name="flexformfield",
            name="field_type",
            field=smart_register.core.compat.StrategyClassField(),
        ),
        migrations.AlterField(
            model_name="flexformfield",
            name="regex",
            field=smart_register.core.compat.RegexField(blank=True, null=True),
        ),
    ]
