# Generated by Django 3.2.12 on 2022-03-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_auto_20220318_0516"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formset",
            name="description",
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
