# Generated by Django 3.2.12 on 2022-03-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_formset_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="formset",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
