# Generated by Django 3.2.12 on 2022-03-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_flexformfield_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="formset",
            name="advanced",
            field=models.JSONField(default=dict),
        ),
    ]
