# Generated by Django 3.2.12 on 2022-03-21 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_formset_advanced"),
    ]

    operations = [
        migrations.AddField(
            model_name="formset",
            name="validator",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"target": "formset"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.validator",
            ),
        ),
        migrations.AlterField(
            model_name="validator",
            name="target",
            field=models.CharField(
                choices=[("form", "Form"), ("field", "Field"), ("formset", "Formset")], max_length=10
            ),
        ),
    ]
