# Generated by Django 3.2.12 on 2022-03-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_auto_20220321_1743"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validator",
            name="target",
            field=models.CharField(
                choices=[("form", "Form"), ("field", "Field"), ("formset", "Formset"), ("module", "Module")],
                max_length=10,
            ),
        ),
    ]
