# Generated by Django 3.2.12 on 2022-04-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_auto_20220328_0647"),
    ]

    operations = [
        migrations.AddField(
            model_name="flexform",
            name="last_update_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="flexformfield",
            name="last_update_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="formset",
            name="last_update_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
