# Generated by Django 3.2.12 on 2022-04-02 11:24

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_auto_20220402_0954"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flexform",
            name="version",
            field=concurrency.fields.AutoIncVersionField(default=0, help_text="record revision number"),
        ),
        migrations.AlterField(
            model_name="flexformfield",
            name="version",
            field=concurrency.fields.AutoIncVersionField(default=0, help_text="record revision number"),
        ),
        migrations.AlterField(
            model_name="formset",
            name="version",
            field=concurrency.fields.AutoIncVersionField(default=0, help_text="record revision number"),
        ),
        migrations.AlterField(
            model_name="optionset",
            name="version",
            field=concurrency.fields.AutoIncVersionField(default=0, help_text="record revision number"),
        ),
    ]
