# Generated by Django 3.2.13 on 2022-05-11 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_auto_20220506_0601"),
    ]

    operations = [
        migrations.RenameField(
            model_name="validator",
            old_name="name",
            new_name="label",
        ),
    ]
