# Generated by Django 3.2.13 on 2022-05-11 04:52

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_rename_name_validator_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="validator",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(
                blank=True, null=True, max_length=255, unique=True, verbose_name="Function Name"
            ),
        ),
        migrations.AlterField(
            model_name="validator",
            name="label",
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255),
        ),
    ]
