# Generated by Django 3.2.13 on 2022-05-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_auto_20220511_0452"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="validator",
            name="message",
        ),
    ]
