# Generated by Django 3.2.13 on 2022-05-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_remove_validator_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validator",
            name="target",
            field=models.CharField(
                choices=[
                    ("form", "Form"),
                    ("field", "Field"),
                    ("formset", "Formset"),
                    ("module", "Module"),
                    ("handler", "Handler"),
                    ("script", "Script"),
                ],
                max_length=10,
            ),
        ),
    ]
