# Generated by Django 3.2.15 on 2022-08-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbtemplates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="name",
            field=models.CharField(
                help_text="Example: 'flatpages/default.html'", max_length=100, unique=True, verbose_name="name"
            ),
        ),
    ]
