# Generated by Django 3.2.16 on 2022-12-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbtemplates", "0002_alter_template_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="active",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
