# Generated by Django 3.2.15 on 2022-08-19 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0037_auto_20220819_0950"),
        ("counters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counter",
            name="registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="counters", to="registration.registration"
            ),
        ),
    ]
