# Generated by Django 3.2.12 on 2022-03-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_registration_public_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="data2",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
