# Generated by Django 3.2.12 on 2022-03-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_record_data2"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="public_key2",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
