# Generated by Django 3.2.12 on 2022-03-12 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0005_auto_20220312_2253"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="data",
        ),
    ]
