# Generated by Django 3.2.12 on 2022-03-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0017_auto_20220329_1713"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="encrypt_data",
            field=models.BooleanField(default=False),
        ),
    ]
