# Generated by Django 3.2.12 on 2022-04-02 10:10

from django.db import migrations

import aurora.registration.models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0021_auto_20220402_0957"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="remote_ip",
            field=aurora.registration.models.RemoteIp(blank=True, null=True),
        ),
    ]
