# Generated by Django 3.2.12 on 2022-04-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0022_record_remote_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="locale",
            field=models.CharField(
                choices=[
                    ("uk-ua", "український | Ukrainian"),
                    ("en-us", "English | English"),
                    ("pl-pl", "Polskie | Polish"),
                ],
                default="en-us",
                max_length=10,
            ),
        ),
    ]
