# Generated by Django 3.2.13 on 2022-04-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0025_auto_20220422_1344"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="footer",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="intro",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
