# Generated by Django 3.2.13 on 2022-05-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0026_auto_20220429_0708"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="slug",
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
