# Generated by Django 3.2.13 on 2022-05-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0028_auto_20220510_0446"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="client_validation",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
