# Generated by Django 3.2.13 on 2022-05-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0030_auto_20220511_1318"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="counters",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="record",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
