# Generated by Django 3.2.15 on 2022-08-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0036_registration_archived"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registration",
            options={"get_latest_by": "start", "permissions": (("can_manage", "Can Manage Registration"),)},
        ),
    ]
