# Generated by Django 3.2.15 on 2022-08-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0037_auto_20220819_0950"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="unique_field",
            field=models.CharField(
                blank=True, help_text="Form field to be used as unique key (DEPRECATED)", max_length=255, null=True
            ),
        ),
    ]
