# Generated by Django 3.2.16 on 2023-03-10 17:15

import aurora.registration.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flatpages", "0001_initial"),
        ("core", "0050_auto_20230307_1139"),
        ("registration", "0037_auto_20220819_0950"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registration",
            options={
                "get_latest_by": "start",
                "ordering": ("name", "title"),
                "permissions": (
                    ("can_manage_registration", "Can manage Registration"),
                    ("register", "Can use Registration"),
                    ("create_translation", "Can Create Translation"),
                    ("export_data", "Can Export Data"),
                    ("can_view_data", "Can View Collected data"),
                ),
            },
        ),
        migrations.RemoveField(
            model_name="registration",
            name="unique_field",
        ),
        migrations.AddField(
            model_name="record",
            name="is_offline",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="registration",
            name="export_allowed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="registration",
            name="is_pwa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="registration",
            name="project",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.project"),
        ),
        migrations.AddField(
            model_name="registration",
            name="protected",
            field=models.BooleanField(
                default=False, help_text="If true, limit access to users with 'registration.register' permission"
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="show_in_homepage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="registration",
            name="welcome_page",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="flatpages.flatpage"
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="locale",
            field=models.CharField(
                choices=[
                    ("en-us", "English | English"),
                    ("ar-ae", " | عربيArabic"),
                    ("cs-cz", "čeština | Czech"),
                    ("de-de", "Deutsch | German"),
                    ("es-es", "Español | Spanish"),
                    ("fr-fr", "Français | French"),
                    ("hu-hu", "Magyar | Hungarian"),
                    ("it-it", "Italiano | Italian"),
                    ("pl-pl", "Polskie | Polish"),
                    ("pt-pt", "Português | Portuguese"),
                    ("ro-ro", "Română | Romanian"),
                    ("ru-ru", "Русский | Russian"),
                    ("si-si", "සිංහල | Sinhala"),
                    ("ta-ta", "தமிழ் | Tamil"),
                    ("uk-ua", "український | Ukrainian"),
                    ("hi-hi", "हिंदी | Hindi"),
                ],
                default="en-us",
                max_length=10,
                verbose_name="Default locale",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="locales",
            field=aurora.registration.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("en-us", "English | English"),
                        ("ar-ae", " | عربيArabic"),
                        ("cs-cz", "čeština | Czech"),
                        ("de-de", "Deutsch | German"),
                        ("es-es", "Español | Spanish"),
                        ("fr-fr", "Français | French"),
                        ("hu-hu", "Magyar | Hungarian"),
                        ("it-it", "Italiano | Italian"),
                        ("pl-pl", "Polskie | Polish"),
                        ("pt-pt", "Português | Portuguese"),
                        ("ro-ro", "Română | Romanian"),
                        ("ru-ru", "Русский | Russian"),
                        ("si-si", "සිංහල | Sinhala"),
                        ("ta-ta", "தமிழ் | Tamil"),
                        ("uk-ua", "український | Ukrainian"),
                        ("hi-hi", "हिंदी | Hindi"),
                    ],
                    max_length=10,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
