# Generated by Django 3.2.16 on 2022-11-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0039_auto_20220930_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'get_latest_by': 'start', 'permissions': (('manage', 'Can manage Registration'), ('register', 'Can use Registration'))},
        ),
        migrations.AddField(
            model_name='registration',
            name='is_pwa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='protected',
            field=models.BooleanField(default=False, help_text="If true, only authenticated 'users' with 'registration.register' permission can use this Module"),
        ),
    ]
