# Generated by Django 3.2.16 on 2022-12-02 10:11

from django.db import migrations, models

import aurora.registration.fields


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0039_auto_20220930_1149"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registration",
            options={
                "get_latest_by": "start",
                "permissions": (("manage", "Can manage Registration"), ("register", "Can use Registration")),
            },
        ),
        migrations.AlterField(
            model_name="registration",
            name="locale",
            field=models.CharField(
                choices=[
                    ("en-us", "English | English"),
                    ("uk-ua", "український | Ukrainian"),
                    ("pl-pl", "Polskie | Polish"),
                    ("ar-ae", " | عربيArabic"),
                    ("es-es", "Español | Spanish"),
                    ("fr-fr", "Français | French"),
                    ("pt-pt", "Português"),
                    ("ta-ta", "தமிழ் | Tamil"),
                    ("si-si", "සිංහල | Sinhala"),
                ],
                default="en-us",
                max_length=10,
                verbose_name="Default locale",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="locales",
            field=aurora.registration.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("en-us", "English | English"),
                        ("uk-ua", "український | Ukrainian"),
                        ("pl-pl", "Polskie | Polish"),
                        ("ar-ae", " | عربيArabic"),
                        ("es-es", "Español | Spanish"),
                        ("fr-fr", "Français | French"),
                        ("pt-pt", "Português"),
                        ("ta-ta", "தமிழ் | Tamil"),
                        ("si-si", "සිංහල | Sinhala"),
                    ],
                    max_length=10,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="protected",
            field=models.BooleanField(
                default=False,
                help_text="If true, limit access to users with 'registration.register' permission",
            ),
        ),
    ]