# Generated by Django 3.2.16 on 2023-01-23 18:56

import django.db.models.deletion
from django.db import migrations, models

import aurora.registration.fields


class Migration(migrations.Migration):

    dependencies = [
        ("flatpages", "0001_initial"),
        ("registration", "0040_auto_20221202_1011"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registration",
            options={
                "get_latest_by": "start",
                "permissions": (
                    ("manage", "Can manage Registration"),
                    ("register", "Can use Registration"),
                    ("create_translation", "Can Create Translation"),
                ),
            },
        ),
        migrations.AddField(
            model_name="registration",
            name="show_in_homepage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="registration",
            name="welcome_page",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="flatpages.flatpage"
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="locale",
            field=models.CharField(
                choices=[
                    ("en-us", "English | English"),
                    ("ar-ae", " | عربيArabic"),
                    ("cs-cz", "čeština | Czech"),
                    ("de-de", "Deutsch"),
                    ("es-es", "Español | Spanish"),
                    ("fr-fr", "Français | French"),
                    ("hu-hu", "Magyar | Hungarian"),
                    ("it-it", "Italiano"),
                    ("pl-pl", "Polskie | Polish"),
                    ("pt-pt", "Português"),
                    ("ro-ro", "Română"),
                    ("si-si", "සිංහල | Sinhala"),
                    ("ta-ta", "தமிழ் | Tamil"),
                    ("uk-ua", "український | Ukrainian"),
                    ("hi-hi", "हिंदी"),
                ],
                default="en-us",
                max_length=10,
                verbose_name="Default locale",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="locales",
            field=aurora.registration.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("en-us", "English | English"),
                        ("ar-ae", " | عربيArabic"),
                        ("cs-cz", "čeština | Czech"),
                        ("de-de", "Deutsch"),
                        ("es-es", "Español | Spanish"),
                        ("fr-fr", "Français | French"),
                        ("hu-hu", "Magyar | Hungarian"),
                        ("it-it", "Italiano"),
                        ("pl-pl", "Polskie | Polish"),
                        ("pt-pt", "Português"),
                        ("ro-ro", "Română"),
                        ("si-si", "සිංහල | Sinhala"),
                        ("ta-ta", "தமிழ் | Tamil"),
                        ("uk-ua", "український | Ukrainian"),
                        ("hi-hi", "हिंदी"),
                    ],
                    max_length=10,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]