# Generated by Django 3.2.16 on 2023-01-31 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0040_auto_20221202_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'get_latest_by': 'start', 'ordering': ('name', 'title'), 'permissions': (('manage', 'Can manage Registration'), ('register', 'Can use Registration'), ('create_translation', 'Can Create Translation'))},
        ),
    ]
