# Generated by Django 3.2.16 on 2023-01-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0040_auto_20221110_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_offline',
            field=models.BooleanField(default=False),
        ),
    ]
