# Generated by Django 3.2.16 on 2023-01-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0042_auto_20230125_0942"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="unique_field",
        ),
    ]
