# Generated by Django 3.2.16 on 2023-02-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0045_auto_20230208_1133"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registration",
            options={
                "get_latest_by": "start",
                "ordering": ("name", "title"),
                "permissions": (
                    ("manage", "Can manage Registration"),
                    ("register", "Can use Registration"),
                    ("create_translation", "Can Create Translation"),
                    ("export_data", "Can Export Data"),
                ),
            },
        ),
        migrations.AddField(
            model_name="registration",
            name="export_allowed",
            field=models.BooleanField(default=False),
        ),
    ]
