# Generated by Django 3.2.16 on 2023-02-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0046_auto_20230208_1611"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="restrict_to_groups",
        ),
    ]
