# Generated by Django 3.2.16 on 2023-03-07 11:39

import aurora.registration.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0047_remove_registration_restrict_to_groups"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registration",
            options={
                "get_latest_by": "start",
                "ordering": ("name", "title"),
                "permissions": (
                    ("can_manage_registration", "Can manage Registration"),
                    ("register", "Can use Registration"),
                    ("create_translation", "Can Create Translation"),
                    ("export_data", "Can Export Data"),
                    ("can_view_data", "Can View Collected data"),
                ),
            },
        ),
        migrations.AlterField(
            model_name="registration",
            name="locale",
            field=models.CharField(
                choices=[
                    ("en-us", "English | English"),
                    ("ar-ae", " | عربيArabic"),
                    ("cs-cz", "čeština | Czech"),
                    ("de-de", "Deutsch | German"),
                    ("es-es", "Español | Spanish"),
                    ("fr-fr", "Français | French"),
                    ("hu-hu", "Magyar | Hungarian"),
                    ("it-it", "Italiano | Italian"),
                    ("pl-pl", "Polskie | Polish"),
                    ("pt-pt", "Português | Portuguese"),
                    ("ro-ro", "Română | Romanian"),
                    ("ru-ru", "Русский | Russian"),
                    ("si-si", "සිංහල | Sinhala"),
                    ("ta-ta", "தமிழ் | Tamil"),
                    ("uk-ua", "український | Ukrainian"),
                    ("hi-hi", "हिंदी | Hindi"),
                ],
                default="en-us",
                max_length=10,
                verbose_name="Default locale",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="locales",
            field=aurora.registration.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("en-us", "English | English"),
                        ("ar-ae", " | عربيArabic"),
                        ("cs-cz", "čeština | Czech"),
                        ("de-de", "Deutsch | German"),
                        ("es-es", "Español | Spanish"),
                        ("fr-fr", "Français | French"),
                        ("hu-hu", "Magyar | Hungarian"),
                        ("it-it", "Italiano | Italian"),
                        ("pl-pl", "Polskie | Polish"),
                        ("pt-pt", "Português | Portuguese"),
                        ("ro-ro", "Română | Romanian"),
                        ("ru-ru", "Русский | Russian"),
                        ("si-si", "සිංහල | Sinhala"),
                        ("ta-ta", "தமிழ் | Tamil"),
                        ("uk-ua", "український | Ukrainian"),
                        ("hi-hi", "हिंदी | Hindi"),
                    ],
                    max_length=10,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
