# Generated by Django 3.2.16 on 2023-02-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0048_auto_20230216_0911"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registration",
            options={
                "get_latest_by": "start",
                "ordering": ("name", "title"),
                "permissions": (
                    ("can_manage_registration", "Can manage Registration"),
                    ("register", "Can use Registration"),
                    ("create_translation", "Can Create Translation"),
                    ("export_data", "Can Export Data"),
                    ("can_view_data", "Can View Collected data"),
                ),
            },
        ),
    ]
