# Generated by Django 3.2.18 on 2023-03-27 12:05

import strategy_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0049_record_registrar"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="dry_run",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="registration",
            name="handler",
            field=strategy_field.fields.StrategyField(blank=True, default=None, null=True),
        ),
    ]
