# Generated by Django 3.2.18 on 2023-11-23 06:05

import django.contrib.postgres.fields.citext
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_auto_20231123_0605"),
        ("registration", "0050_auto_20230327_1205"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="registration",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="registrations", to="core.project"
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="slug",
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="registration",
            unique_together={("name", "project")},
        ),
    ]
